#!/bin/bash

if [ ! -f /etc/httpd/Apache/Authn/Redmine.pm ]
then
  mkdir -p /etc/httpd/Apache/Authn
  cp $INSTALL_DIR/extra/svn/Redmine.pm /etc/httpd/Apache/Authn/
fi

if [ "$SSL" = "y" ]; then REPLACE_SSL="#SSL# *"; fi
if [ "$ENABLE_JENKINS" = "y" ]; then REPLACE_JENKINS="#JENKINS# *"; fi
if [ "$ALMINIUM_SUBDIR" = "y" ]; then REPLACE_DIR="#SUBDIR# *"; else REPLACE_DIR="#NO_SUBDIR# *"; fi
for FILE in $(ls etc/ | grep '.conf$')
do
  sed -e "s|#HOSTNAME#|$HOSTNAME|" \
      -e "s|#$OS# *||" \
      -e "s|$REPLACE_SSL||" \
      -e "s|$REPLACE_JENKINS||" \
      -e "s|$REPLACE_DIR||" \
      "etc/$FILE" > "$ALM_ETC_DIR/$FILE"
done

ln -sf "$ALM_ETC_DIR/passenger.conf" "$APACHE_CONF_DIR/"
ln -sf "$ALM_ETC_DIR/alminium.conf"  "$APACHE_CONF_DIR/"

#log rotate
cp $ALM_ETC_DIR/alminium-logrotate /etc/logrotate.d/alminium

# セキュリティ無効化の設定
if [ ! "$USE_DISABLE_SECURITY" = "n" ]
then
  # SELinuxを無効化
#  echo 0 > /selinux/enforce
  CHK=`grep SELINUX=enforcing /etc/selinux/config`
  if [ ! "$CHK" = '' ]
  then
    sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config 
    echo "SELinuxが無効化されました"
  fi

  # ファイアウォールの設定で80番(http)および443番(https)を許可
  firewall-cmd --add-service=http --add-service=https --zone=public --permanent
  firewall-cmd --reload
  firewall-cmd --list-all
#  CHK=`grep "dport 80" /etc/sysconfig/iptables`
#  if [ "$CHK" = '' ]
#  then
#    RULENUM=`iptables-save |grep INPUT |grep -n "dport 22"|awk -F : '{print $1}'`
#    iptables -I  INPUT ${RULENUM} -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
#    iptables-save > /etc/sysconfig/iptables
#    echo "tcp 80番ポートのアクセスを許可しました"
#  fi
#  CHK=`grep "dport 443" /etc/sysconfig/iptables`
#  if [ "$CHK" = '' ]
#  then
#    RULENUM=`iptables-save |grep INPUT |grep -n "dport 22"|awk -F : '{print $1}'`
#    iptables -I  INPUT ${RULENUM} -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
#    iptables-save > /etc/sysconfig/iptables
#    echo "tcp 443番ポートのアクセスを許可しました"
#  fi
fi

# MariaDB設定
CHK=`grep "character-set-server=utf8" /etc/my.cnf`
if [ "$CHK" = "" ]
then
  mv /etc/my.cnf /etc/my.cnf.org
  cat /etc/my.cnf.org | sed -e "s/\[mysqld_safe\]/character-set-server=utf8\n\n\[mysqld_safe\]/g" > /etc/my.cnf
  echo -e "\n[mysql]\ndefault-character-set=utf8\n" >> /etc/my.cnf
fi

chkconfig --add httpd
chkconfig httpd on
service httpd stop
service httpd start
