#!/bin/bash

# check user
if [ `whoami` != 'root' ]; then
    echo "ALMiniumのインストールはルートユーザで行う必要があります。"
    echo "rootユーザもしくはsudoで実行してください。"
    exit 1
fi

# start services
docker-compose -f ../test-docker-compose.yml up -d
echo >> supervisord.conf
echo [program:jenkins] >> supervisord.conf
echo startretries=10 >> supervisord.conf
echo command=service jenkins start >> supervisord.conf

# test
sleep 90 && curl -k https://localhost:14443/alminium/
curl -k https://localhost:14443/jenkins/

