#!/bin/bash
############################################################
# backup for ALMinium.
# 第一引数：バックアップディレクトリ
############################################################

if [ "$1" = "" ]
then
  echo "バックアップディレクトリ(第一引数)を指定してください"
  exit 1
fi

ALM_CURRENT_DIR=`pwd`
if [ `echo $1 | cut -c 1` = '/' ]
then
  ALM_BACKUP_DIR=$1
else
  ALM_BACKUP_DIR=$ALM_CURRENT_DIR/$1
fi

# 実行ユーザーチェック
if [ "$USER" != 'root' ]
then
  echo -n "本処理はルートユーザで行う必要があります。"
  echo "rootユーザもしくはsudoで実行してください。"
  exit 1
fi

#バックアップディレクトリのチェック
if [ ! -d $ALM_BACKUP_DIR ]
then
  echo "バックアップディレクトリが見つかりませんでした。処理を中止します"
  exit 1
fi

# バックアップファイル名決定
ALM_BACKUP_ID=`date +"%Y-%m-%d-%H-%M-%S"`
ALM_DBBACKUP_NAME=db.dump
ALM_FILE_BACKUP=files.tar.gz
ALM_REPOS_BACKUP=repo.tar.gz
ALM_BACKUP_NAME=$ALM_BACKUP_DIR/${ALM_BACKUP_ID}-alm-backup.tar.gz

#データベースをバックアップ
echo "MySQLデータベースをバックアップします。"
mysqldump -uroot alminium > $ALM_BACKUP_DIR/$ALM_DBBACKUP_NAME
if [ -f $ALM_BACKUP_DIR/$ALM_DBBACKUP_NAME ]
then
  echo "MySQLデータベースのバックアップが成功しました。"
else
  echo "MySQLデータベースのバックアップが失敗しました。"
  exit 1
fi

#redmineの添付ファイルをバックアップ
echo "Redmineの添付ファイルをバックアップします。"
cd /opt/alminium/files/
tar czf $ALM_BACKUP_DIR/$ALM_FILE_BACKUP .
if [ -f $ALM_BACKUP_DIR/$ALM_FILE_BACKUP ]
then
  echo "Redmineの添付ファイルのバックアップが成功しました。"
else
  echo "Redmineの添付ファイルのバックアップが失敗しました。"
  exit 1
fi

#ソースコードリポジトリ
echo "ソースコードリポジトリをバックアップします。"
cd /var/opt/alminium/
tar czf $ALM_BACKUP_DIR/$ALM_REPOS_BACKUP .
if [ -f $ALM_BACKUP_DIR/$ALM_REPOS_BACKUP ]
then
  echo "ソースコードリポジトリのバックアップが成功しました。"
else
  echo "ソースコードリポジトリのバックアップが失敗しました。"
  exit 1
fi

# バックアップ統合
cd $ALM_BACKUP_DIR
echo #################################
pwd
echo #################################
tar czf $ALM_BACKUP_NAME ./$ALM_DBBACKUP_NAME ./$ALM_FILE_BACKUP ./$ALM_REPOS_BACKUP

