#!/bin/bash

# OSを確認
if [ -f /etc/redhat-release ]; then
    APACHE_USER=apache
    APACHE_CONF_DIR=/etc/httpd/conf.d
    MYSQLD='/etc/init.d/mysqld'
    MYSQL='mysql'
    CHK=`egrep "CentOS release 5|Red Hat Enterprise Linux .* 5" /etc/redhat-release`
    if [ "$CHK" != '' ]; then
        OS='rhel5'
        echo "RHEL 5.x / CentOS 5.x / OEL 5.xが検出されました。"
        echo "RHEL 5.x / CentOS 5.x / OEL 5.xは、サポートされていません。"
        echo "インストールを中止します。"
        exit 1
    fi
    CHK=`egrep "CentOS Linux release 7" /etc/redhat-release`
    if [ "$CHK" != '' ]; then
        OS='rhel7'
        echo "CentOS 7.x が検出されました。"
        MYSQLD='service mariadb'
        ETH0=enp0s3
    else
        OS='rhel6'
        echo "CentOS 6.xが検出されました。"
        #echo "RHEL 6.x / CentOS 6.x / OEL 6.xが検出されました。"
    fi
#elif [ -f /etc/system-release ]; then
#    APACHE_USER=apache
#    APACHE_CONF_DIR=/etc/httpd/conf.d
#    MYSQLD='/etc/init.d/mysqld'
#    MYSQL='mysql'
#    CHK=`egrep "Amazon Linux AMI" /etc/system-release`
#    if [ "$CHK" != '' ]; then
#        OS='rhel6'
#        echo "Amazon Linux AMIが検出されました。"
#    fi
elif [ -f /etc/debian_version -a "`grep 14.04 /etc/issue`" != "" ]; then
    APACHE_USER=www-data
    APACHE_CONF_DIR=/etc/apache2/conf.d
    MYSQLD='/etc/init.d/mysql'
    MYSQL='mysql'
    OS='debian'
    echo "Ubuntu 14.04 が検出されました。"
elif [ -f /etc/lsb-release -a "`grep 16.04 /etc/lsb-release`" != "" ]; then
    APACHE_USER=www-data
    APACHE_CONF_DIR=/etc/apache2/conf.d
    MYSQLD='/etc/init.d/mysql'
    MYSQL='mysql'
    OS='ubuntu1604'
    ETH0=enp0s3
    if [ ! -f jenkins/setup/ubuntu1604 ]; then
      ln -s debian jenkins/setup/ubuntu1604
    fi
    echo "Ubuntu 16.04 が検出されました。"
else
    #CHK=`sw_vers | awk '$1 = "ProductName"{ _OS = $2 " " $3 " " $4; getline; print _OS,$2; exit }'`
    #if [ "$CHK" != '' ]; then
    #  APACHE_USER=www
    #  APACHE_CONF_DIR=/opt/local/apache2/conf
    #  MYSQLD=/opt/local/share/mysql55/support-files/mysql.server
    #  MYSQL=mysql
    #  OS='mac'
    #  CPCMD='cp -Rf'
    #  RMCMD='rm -Rf'
    #  echo "${CHK}が検出されました。"
    #else
      echo "サポートされていないOSです。"
      echo "現在サポートされいているOSは、"
      echo ""
      echo "  * Ubuntu 14.04/16.04"
      echo "  * CentOS 6.0/7.0"
      #echo "  * Debian GNU/Linux 6.0"
      #echo "  * RHEL/Oracle EL/CentOS/SL 6.0/6.1"
      #echo "  * Amazon Linux AMI"
      #echo "  * Mac OS X 10.7"
      echo "です。"
      exit
    #fi
fi

