#!/bin/bash
#########################################
# restore from ALMinium's backup.       #
# 第一引数：バックアップファイル名      #
# 第2引数：データベースホスト名         #
# 第3引数：データベース管理者パスワード #
#########################################

ALM_DB_HOST=${ALM_DB_HOST:-$2}
ALM_DB_HOST=${ALM_DB_HOST:-localhost}
ALM_DB_ROOT_PASS=${ALM_DB_ROOT_PASS:-$3}

ALM_CURRENT_DIR=${ALM_CURRENT_DIR:-`pwd`}

# 実行ユーザーをチェック
if [ "`whoami`" != 'root' ]; then
    echo "ALMiniumのインストールはルートユーザで行う必要があります。"
    echo "rootユーザもしくはsudoで実行してください。"
    exit 1
fi

# バックアップファイルをチェック
if [ "$1" = "" ]; then
    echo "第一引数にバックアップファイルを指定してください。"
    exit 1
fi

if [ ! -f "$1" ]; then
  echo "指定したバックアップファイルが在りません。処理を中止します。"
fi

ALM_BACKUP_NAME=$1
ALM_DBBACKUP_NAME=/tmp/db.dump
ALM_FILE_BACKUP=/tmp/files.tar.gz
ALM_REPOS_BACKUP=/tmp/repo.tar.gz

# include functions
source inst-script/functions

# バックアップの復元
echo "${ALM_BACKUP_NAME}を復元します。"
cd /tmp
tar xzf $ALM_BACKUP_NAME

echo "***リポジトリーデータを復元しています..."
cd /var/opt/alminium/ && tar xzf $ALM_REPOS_BACKUP
echo "***Redmine添付ファイルを復元しています..."
cd /opt/alminium/files/ && tar xzf $ALM_FILE_BACKUP
if [ "$ALM_DB_RESTORE" != "no" ]; then
  echo "***データベースを復元しています..."
  mysql `db_option` alminium < $ALM_DBBACKUP_NAME
  echo "データ復元が完了しました。"
  #データベースのマイグレーション
  echo "データベースのマイグレーションを実施します。"
  cd /opt/alminium
  bundle exec rake db:migrate RAILS_ENV=production
  bundle exec rake redmine:plugins:migrate RAILS_ENV=production
  bundle exec rake tmp:cache:clear RAILS_ENV=production
  bundle exec rake tmp:sessions:clear RAILS_ENV=production
  echo "データベースのマイグレーションが完了しました。"
fi

cd $ALM_CURRENT_DIR
if [ -f service-restart ]; then
  echo "サービスを再起動します。"
  source ./service-restart
elif [ -f inst-script/service-restart ]; then
  echo "サービスを再起動します。"
  source ./inst-script/service-restart
else
  echo "サービスを再起動してください。"
fi

