#!/bin/bash

GEM=`which gem2.0`
GEM=${GEM:-gem}
ALM_ETC_DIR=${ALM_ETC_DIR:-/etc/opt/alminium}
ALM_VAR_DIR=${ALM_VAR_DIR:-/var/opt/alminium}
ALM_INSTALL_DIR=${ALM_INSTALL_DIR:-/opt/alminium}

echo "ALMiniumをアンインストールします。"
echo ""
echo -n "データベース(全てのRedmineの情報)とリポジトリを削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]; then
    mysql alminium -e "REVOKE ALL ON alminium.* FROM alminium@localhost"
    mysql alminium -e "DELETE FROM mysql.user WHERE User LIKE 'alminium'"
    mysql alminium -e "FLUSH PRIVILEGES"
    mysql alminium -e "DROP DATABASE alminium"
    rm -fr $ALM_INSTALL_DIR/* $ALM_INSTALL_DIR/.[^.]*  $ALM_VAR_DIR/*
fi

echo ""
echo -n "Apacheの設定を削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]; then
    rm -fr /etc/httpd/conf.d/{alminium}.conf
    rm -fr /etc/apache2/conf.d/{alminium}.conf
    rm -fr /etc/apache2/sites-{available,enabled}/alminium.conf
    rm -fr $ALM_ETC_DIR/*
fi


echo ""
echo -n "Jenkisとその設定を削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]; then
    source jenkins/setup/uninstall.sh
fi


echo ""
echo -n "キャッシュされたファイルを削除しますか?(y/N)"
read YN

if [ "$YN" = "y" ]; then
    rm -fr cache *.installed
fi
