#!/bin/bash
############################################################
# upgrader for ALMinium.
############################################################

export CURRENT_DIR=`pwd`
export FIRST_CHAR_BACKUP_DIR=`echo $1 | cut -c 1`
if [ "$FIRST_CHAR_BACKUP_DIR" = '/' ]
then
  export BACKUP_DIR=$1
else
  export BACKUP_DIR=$CURRENT_DIR/$1
fi

export DBBACKUP_NAME=$BACKUP_DIR/alminiumDB-`date +"%Y-%m-%d-%H-%M-%S"`.dump
export FILE_BACKUP=$BACKUP_DIR/opt_alminium_files-`date +"%Y-%m-%d-%H-%M-%S"`.tar.gz
export REPOS_BACKUP=$BACKUP_DIR/var_opt_alminium-`date +"%Y-%m-%d-%H-%M-%S"`.tar.gz

./backup $1

#バックアップの確認
echo ""
echo "指定したディレクトリにバックアップデータ(データベース：alminiumDB-(日時).dump, 添付ファイル：opt_alminium_files-(日時).tar.gz, リポジトリ：var_opt_alminium-(日時).tar.gz)が作成されていることを確認してください。問題がなければEnterキーを押下してください。中止する場合はCtrl+C。"
echo "#### 何らかのエラーがコンソールに出力されている場合はバックアップに失敗している可能性がありますので、中止(Ctrl+C)してください。"
echo "#### エラー発生等により中止した場合は、upgradeファイルを参考に手動によりアップグレードを実行することをお勧めします。"
read DO_CONTINUE

#alminiumを再インストールする。
echo ""
echo ""
echo "ALMiniumのアンインストールを開始します。問い合わせに対してはすべて'y'を選んでください"
echo "処理を継続する場合は何らかのキーを押下してください。"
read DO_CONTINUE

cd $CURRENT_DIR
./uninstall

#install
echo "ALMiniumのインストールを開始します。"
cd $CURRENT_DIR
./smelt
service apache2 stop

echo "バックアップデータを復元します。"
#バックアップの復元
cd $CURRENT_DIR
cd /var/opt/alminium/ && tar xzf $REPOS_BACKUP
cd /opt/alminium/files/ && tar xzf $FILE_BACKUP
mysql -uroot alminium < $DBBACKUP_NAME


#データベースのマイグレーション
cd /opt/alminium
rake db:migrate RAILS_ENV="production"
rake redmine:plugins:migrate RAILS_ENV=production
rake tmp:cache:clear
rake tmp:sessions:clear

service apache2 start

