#!/bin/bash
############################################################
# upgrader for ALMinium.
############################################################

ALM_INSTALL_DIR=/opt/alminium
ALM_CURRENT_DIR=`pwd`
ALM_ETC_DIR=/etc/opt/alminium

# 実行ユーザーをチェック
if [ "$USER" != 'root' ]
then
    echo "ALMiniumのインストールはルートユーザで行う必要があります。"
    echo "rootユーザもしくはsudoで実行してください。"
    exit 1
fi

# ALMiniumインストール状況をチェック
if [ ! -d $ALM_INSTALL_DIR ]
then
  echo "ALMiniumインストールディレクトリが見つかりませんでした。処理を中止します"
  exit 1
fi

# バックアップディレクトリ指定をチェック
if [ "$1" = '' ]
then
    echo "第一引数にバックアップディレクトリを指定してください。"
    exit 1
fi

# バックアップの確認 
echo "#####################################################################"
echo "# 途中にエラーが発生した場合、復活できなくなる可能性があるため、    #"
echo "# スナップショットをとるなど、後戻りできるようにしておいてください。#"
echo "# また、ご自身によるカスタマイズ（プラグイン、設定ファイル等）があ  #"
echo "# る場合は、アップグレードすることにより削除・上書きされてしまいま  #"
echo "# すので、アップグレード後に手動でカスタマイズを実行する必要があり  #"
echo "# ます。処理を続行する場合はEnterキーを押下してください。           #"
echo "#####################################################################"
read DO_CONTINUE

# バックアップ
if [ `echo $1 | cut -c 1` = '/' ]
then
  ALM_BACKUP_DIR=$1
else
  ALM_BACKUP_DIR=$ALM_CURRENT_DIR/$1
fi
source ./backup $1 
if [ $? -gt 0 ]
then
  echo "バックアップに失敗したため、処理を中止します"
  exit 1
fi

#バックアップの確認依頼
echo ""
echo "指定したディレクトリにバックアップデータ(データベース：alminiumDB-(日時).dump, 添付ファイル：opt_alminium_files-(日時).tar.gz, リポジトリ：var_opt_alminium-(日時).tar.gz)が作成されていることを確認してください。問題がなければEnterキーを押下してください。中止する場合はCtrl+C。"
echo "#### 何らかのエラーがコンソールに出力されている場合はバックアップに失敗している可能性がありますので、中止(Ctrl+C)してください。"
echo "#### エラー発生等により中止した場合は、upgradeファイルを参考に手動によりアップグレードを実行することをお勧めします。"
read DO_CONTINUE

#
# alminium再インストール
# 
echo ""
echo ""
echo "ALMiniumのアップグレードを開始・・・"

# アップグレード対象を削除
cd $ALM_CURRENT_DIR
if [ -f $ALM_INSTALL_DIR/subdirname ]
then
  rm -f /var/www/html`cat $ALM_INSTALL_DIR/subdirname`
fi
rm -fr $ALM_INSTALL_DIR
rm -fr cache/* *.installed
rm -fr $ALM_ETC_DIR/passenger.*
#　install ALMinium by smelt
source ./smelt -u

#バックアップの復元
source ./restore $ALM_BACKUP_NAME

echo ""
echo "以上でアップグレードは終了です。途中にエラーが発生した場合は、元の状態に戻して手動でアップグレードを実施してください。"

