#!/bin/bash
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
USER=root
MAILTO=root

ALM_BACKUP_CMD=/opt/alminium/backup
ALM_BACKUP_DIR=#ALM_BACKUP_DIR#
ALM_BACKUP_LOG=#ALM_BACKUP_LOG#

#ALM_BACKUP_MINUTE# #ALM_BACKUP_HOUR# #ALM_BACKUP_DAY# * * root ALM_BACKUP_EXPIRY=#ALM_BACKUP_EXPIRY# $ALM_BACKUP_CMD $ALM_BACKUP_DIR >> $ALM_BACKUP_LOG


