#!/bin/bash
#
#

echo "*** create ALMinium DB ***"

# ALMiniumインストールディレクトリへ移動
pushd ${ALM_INSTALL_DIR}

# create db
if [ "${ALM_UPGRADE}" != "y" ]; then
  DB_OPTION="`db_option`"
  EXIT_ALM_DB="`mysql ${DB_OPTION} -e \"status\" alminium`"
  if [ "${EXIT_ALM_DB}" = "" ]; then
    DB_OPTION_ROOT="`db_option_root`"
#    ACCESS_MYSQL="`mysql ${DB_OPTION_ROOT} -e \"status\" mysql`"
#    if [ "${ACCESS_MYSQL}" != "" ]; then
    if [ "`db_test`" != "" ]; then
      # create DB
      mysql `db_option_root` < ${ALM_SRC_DIR}/redmine/setup/createdb.sql
    else
      echo "データベースを作成作成することが出来ません。データベースへのアクセス
権の設定を確認してください。"
      exit 1
    fi
  fi
fi

popd

