#!/bin/bash
#
# プラグインをインストールすると同時にRedmineの初期設定を行う
#

# インストールするディレクトリ名
DEST_NAME=(`grep -v "^#" redmine/setup/redmine-plugins.lst | awk -F, '{print $1}'`)

# 展開したアーカイブのディレクトリ名 or タグ名
DIR_NAME=(`grep -v "^#" redmine/setup/redmine-plugins.lst | awk -F, '{print $2}'`)

# URL
URL_NAME=(`grep -v "^#" redmine/setup/redmine-plugins.lst | awk -F, '{print $3}'`)

for (( i = 0; i < ${#DIR_NAME[@]}; ++i ))
do
  FILE_NAME=`echo ${URL_NAME[$i]} | sed -e "s/.*\/\(.*$\)/\1/"`
  EXT=`echo ${URL_NAME[$i]} | sed -e "s/.*\.\(.*$\)/\1/"`
    case ${EXT} in
    zip)
        if [ ! -f cache/${FILE_NAME} ]; then
          wget -P cache ${URL_NAME[$i]}
        fi
        yes | unzip -q cache/${FILE_NAME}
         rm -fr ${ALM_INSTALL_DIR}/plugins/${DEST_NAME[$i]}
        mv ${DIR_NAME[$i]} ${ALM_INSTALL_DIR}/plugins/${DEST_NAME[$i]}
        rm -f ${FILE_NAME}
        ;;

    tgz|gz)
        if [ ! -f cache/${FILE_NAME} ]; then
          wget -P cache ${URL_NAME[$i]}
        fi
        tar zxf cache/${FILE_NAME}
        rm -fr  ${ALM_INSTALL_DIR}/plugins/${DEST_NAME[$i]}
        mv ${DIR_NAME[$i]} ${ALM_INSTALL_DIR}/plugins/${DEST_NAME[$i]}
        rm -f ${FILE_NAME}
        ;;
    git)
        if [ ! -d cache/${DEST_NAME[$i]} ]; then
          git clone ${URL_NAME[$i]} cache/${DEST_NAME[$i]}
        fi
        if [ -d cache/${DEST_NAME[$i]} ]; then
          cd cache/${DEST_NAME[$i]}
          git checkout ${DIR_NAME[$i]}
          cd ../..
          rm -fr  ${ALM_INSTALL_DIR}/plugins/${DEST_NAME[$i]}
          cp -fra cache/${DEST_NAME[$i]} ${ALM_INSTALL_DIR}/plugins/
        fi
        ;;
    *)
        if [ ! -d cache/${DEST_NAME[$i]} ]; then
          if [[ ${URL_NAME[$i]} =~ "bitbucket.org" ]]; then
            hg clone ${URL_NAME[$i]} cache/${DEST_NAME[$i]}
            cd cache/${DEST_NAME[$i]}
            hg checkout ${DIR_NAME[$i]}
            cd ../..
          else
            svn co ${URL_NAME[$i]} cache/${DEST_NAME[$i]}
            if [ "${DIR_NAME[$i]}" != "HEAD" ]; then
              cd cache/${DEST_NAME[$i]}
              svn update -r ${DIR_NAME[$i]}
              cd ../..
            fi
          fi
        fi
        rm -fr  ${ALM_INSTALL_DIR}/plugins/${DEST_NAME[$i]}
        cp -fra cache/${DEST_NAME[$i]} ${ALM_INSTALL_DIR}/plugins/${DEST_NAME[$i]}
        ;;
    esac
done

# ALMiniumインストールディレクトリへ移動
pushd ${ALM_INSTALL_DIR}

# for Hudson
if [ -f plugins/redmine_hudson/Gemfile ]; then
  mv plugins/redmine_hudson/Gemfile plugins/redmine_hudson/Gemfile.org
fi

# for DMSF
# avoid bandle install error because of rubyzip version conflict
if [ -f ${ALM_INSTALL_DIR}/plugins/redmine_dmsf/Gemfile ]; then
  sed -i.org "s/gem 'rubyzip',/gem 'rubyzip'#,/" ${ALM_INSTALL_DIR}/plugins/redmine_dmsf/Gemfile
fi

# for OAuth2認証
cd ./plugins
case ${ALM_OAUTH2_METHOD} in
google)
  git clone -b master https://github.com/twinslash/redmine_omniauth_google.git
  ;;
github)
  git clone -b v0.0.3 https://github.com/ares/redmine_omniauth_github.git
  ;;
gitlab)
  git clone -b 0.0.1 https://github.com/ayapapa/redmine_omniauth_gitlab.git
  ;;
azure)
  git clone -b master https://github.com/sohelzerdoumi/redmine_omniauth_azure.git
  ;;
esac
cd ..

# ディレクトリを元に戻す
popd

