#!/bin/bash

apt-get -qq update

# add passenger to APT repository
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
apt-get install -y ca-certificates
apt-get install -y --force-yes apt-transport-https
echo deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main > /etc/apt/sources.list.d/passenger.list
chown root: /etc/apt/sources.list.d/passenger.list
# remove old passenger's info 
if [ "`ls /etc/apache2/mods-available/passenger.load 2>/dev/null`" != "" \
     -a ! -f /etc/apache2/mods-available/passenger.load ]; then
  rm -f /etc/apache2/mods*/passenger.*
fi
#  set passenger-package available
ALM_PASSSENGER_PACKAGE_AVAILABLE=1

# install APT packages
if [ "$GIT_UPDATE" = "y" ]; then
  add-apt-repository -y ppa:git-core/ppa
fi
apt-get -qq update
apt-get -y install `grep -v "^#" inst-script/$OS/packages.lst`

REALLY_GEM_UPDATE_SYSTEM=1 gem update --system

# SSL
if [ "$ALM_ENABLE_SSL" = "y" ]; then
    apt-get -y install ssl-cert
    a2enmod ssl rewrite
else
    a2dismod ssl
fi

service mysql start
