#!/bin/bash
# setup database

if [ "$ALM_UPGRADE" = "" ]; then
  # create DB
  mysql `db_option` < redmine/setup/createdb.sql
  # create directory for vcs
  mkdir -p $ALM_VAR_DIR/{git,svn,hg,maven,github}
  chown -R $APACHE_USER:$APACHE_USER $ALM_VAR_DIR/*
fi

