#!/bin/bash
#
# install Redmine
#

# download and put alminium's home dir
mkdir -p $ALM_INSTALL_DIR
echo "*** install Redmine ***"
cd cache
wget $RM_ARC
if [ ! -f redmine-$RM_VER ]; then
  tar zxf $RM_VER.tar.gz
fi
cd ..
cp -fr cache/redmine-$RM_VER/* $ALM_INSTALL_DIR/
rm -fr cache/redmine-$RM_VER

# put config files
cp -f  redmine/Gemfile.local   $ALM_INSTALL_DIR/
cp -fr redmine/config/*        $ALM_INSTALL_DIR/config/
cp -fr redmine/public/themes/* $ALM_INSTALL_DIR/public/themes/
cp     ./{backup,restore} ./inst-script/config-backup \
       ./inst-script/$OS/service-restart $ALM_INSTALL_DIR/

# avoid bandle install error because of nokogiri version conflict
mv $ALM_INSTALL_DIR/Gemfile $ALM_INSTALL_DIR/Gemfile.org
sed "s/gem \"nokogiri\", \">= 1.6.7.2\"/gem \"nokogiri\"#, \">= 1.6.7.2\"/" $ALM_INSTALL_DIR/Gemfile.org > $ALM_INSTALL_DIR/Gemfile

# install plugins
echo "*** install plugins ***"
source redmine/setup/redmine-plugins

if [ "$ALM_UPGRADE" = "" ]; then
  # Customize
  echo "*** run initialize SQL ***"
  $MYSQL alminium < redmine/setup/init.mysql
fi

# install hooks
mkdir -p $ALM_INSTALL_DIR/bin
cp -fr redmine/bin/* $ALM_INSTALL_DIR/bin/
if [ "$ALM_SUBDIR" != "" ]; then
  sed -i "s|localhost|localhost$ALM_SUBDIR|g" $ALM_INSTALL_DIR/bin/alm-sync-scm
  chmod +x $ALM_INSTALL_DIR/bin/alm-sync-scm
fi
cp -fr   redmine/hooks $ALM_INSTALL_DIR/
chown -R $APACHE_USER:$APACHE_USER $ALM_INSTALL_DIR/*

# config default settings
# default host_name(hostname and path)
if [ "$ALM_SUBDIR" = "" ]; then
  HOST_NAME_AND_PATH=$ALM_HOSTNAME
else
  HOST_NAME_AND_PATH=$ALM_HOSTNAME/$ALM_SUBDIR
fi
sed -i "s|default: localhost:3000|default: $HOST_NAME_AND_PATH|" \
       $ALM_INSTALL_DIR/config/settings.yml
# default protocol
if [ "$ALM_ENABLE_SSL" = "y" ]; then
  sed -i "s/default: http/default: https/" $ALM_INSTALL_DIR/config/settings.yml
fi

