#!/bin/bash
#
# install Redmine
#
mkdir -p $ALM_INSTALL_DIR
echo "*** install Redmine ***"
cd cache
wget $RM_ARC
if [ ! -f redmine-$RM_VER ]; then
  tar zxf $RM_VER.tar.gz
fi
cd ..

$CPCMD cache/redmine-$RM_VER/* $ALM_INSTALL_DIR/
$RMCMD cache/redmine-$RM_VER

cp     redmine/Gemfile.local   $ALM_INSTALL_DIR/
$CPCMD redmine/config/*        $ALM_INSTALL_DIR/config/
$CPCMD redmine/public/themes/* $ALM_INSTALL_DIR/public/themes/
cp ./{backup,restore} ./inst-script/config-backup ./inst-script/$OS/service-restart $ALM_INSTALL_DIR/

# avoid bandle install error because of nokogiri version conflict
mv $ALM_INSTALL_DIR/Gemfile $ALM_INSTALL_DIR/Gemfile.org
sed "s/gem \"nokogiri\", \">= 1.6.7.2\"/gem \"nokogiri\"#, \">= 1.6.7.2\"/" $ALM_INSTALL_DIR/Gemfile.org > $ALM_INSTALL_DIR/Gemfile

# install plugins
echo "*** install plugins ***"
source redmine/setup/redmine-plugins

if [ "$ALM_UPGRADE" = "" ]; then
  # Customize
  echo "*** run initialize SQL ***"
  $MYSQL alminium < redmine/setup/init.mysql
fi

# install hooks
mkdir -p $ALM_INSTALL_DIR/bin
$CPCMD redmine/bin/* $ALM_INSTALL_DIR/bin/
if [ "$ALM_SUBDIR" != "" ]; then
  sed -i "s|localhost|localhost$ALM_SUBDIR|g" $ALM_INSTALL_DIR/bin/alm-sync-scm
  chmod +x $ALM_INSTALL_DIR/bin/alm-sync-scm
fi
$CPCMD redmine/hooks $ALM_INSTALL_DIR/
chown -R $APACHE_USER:$APACHE_USER $ALM_INSTALL_DIR/*

