#!/bin/bash

# Apache configs
if [ "$ALM_ENABLE_SSL" = "y" ]; then REPLACE_SSL="#SSL# *"; fi
if [ "$ALM_ENABLE_JENKINS" = "y" ]; then REPLACE_JENKINS="#JENKINS# *"; fi
if [ "$ALM_SUBDIR" = "" ]
then
  DOCMENT_ROOT="/opt/alminium/public"
else
  DOCMENT_ROOT="/var/www/html\nRailsBaseURI $ALM_SUBDIR"
fi

for FILE in $(ls etc/ | grep '.conf$')
do
  sed -e "s|#HOSTNAME#|$ALM_HOSTNAME|" \
      -e "s|#$OS# *||" \
      -e "s|$REPLACE_SSL||" \
      -e "s|$REPLACE_JENKINS||" \
      -e "s|#SUBDIR#|$ALM_SUBDIR|" \
      -e "s|#DOCUMENTROOT#|$DOCMENT_ROOT|" \
      "etc/$FILE" > "$ALM_ETC_DIR/$FILE"
done

# log rotate
cp $ALM_ETC_DIR/alminium-logrotate /etc/logrotate.d/alminium

# OS depend installing
source inst-script/$OS/post-install

# restart service
source inst-script/service-restart

# vim: set ts=2 sw=2 et:
