#!/bin/bash

# set Redmine.pm
mkdir -p /etc/perl/Apache/Authn
rm -f /etc/perl/Apache/Authn/Redmine.pm
ln -s $INSTALL_DIR/extra/svn/Redmine.pm /etc/perl/Apache/Authn/Redmine.pm

# Apache configs
if [ "$SSL" = "y" ]; then REPLACE_SSL="#SSL# *"; fi
if [ "$ENABLE_JENKINS" = "y" ]; then REPLACE_JENKINS="#JENKINS# *"; fi
if [ "$ALMINIUM_SUBDIR" = "y" ]; then REPLACE_DIR="#SUBDIR# *"; else REPLACE_DIR="#NO_SUBDIR# *"; fi
for FILE in $(ls etc/ | grep '.conf$')
do
  sed -e "s|#HOSTNAME#|$HOSTNAME|" \
      -e "s|#$OS# *||" \
      -e "s|$REPLACE_SSL||" \
      -e "s|$REPLACE_JENKINS||" \
      -e "s|$REPLACE_DIR||" \
      "etc/$FILE" > "$ALM_ETC_DIR/$FILE"
done

ln -sf "$ALM_ETC_DIR/passenger.conf" "$APACHE_CONF_DIR/"
ln -sf "$ALM_ETC_DIR/alminium.conf"  "$APACHE_CONF_DIR/"

# log rotate
cp $ALM_ETC_DIR/alminium-logrotate /etc/logrotate.d/alminium

# セキュリティ無効化の設定
if [ ! "$USE_DISABLE_SECURITY" = "n" ]
then
  # SELinuxを無効化
  echo 0 > /selinux/enforce
  CHK=`grep SELINUX=enforcing /etc/selinux/config`
  if [ ! "$CHK" = '' ]
  then
    sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config 
    echo "SELinuxが無効化されました"
  fi

  # ファイアウォールの設定で80番(http)を許可
  CHK=`grep "dport 80" /etc/sysconfig/iptables`
  if [ "$CHK" = '' ]
  then
    RULENUM=`iptables-save |grep INPUT |grep -n "dport 22"|awk -F : '{print $1}'`
    iptables -I  INPUT ${RULENUM} -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
    iptables-save > /etc/sysconfig/iptables
    echo "tcp 80番ポートのアクセスを許可しました"
  fi
  CHK=`grep "dport 443" /etc/sysconfig/iptables`
  if [ "$CHK" = '' ]
  then
    RULENUM=`iptables-save |grep INPUT |grep -n "dport 22"|awk -F : '{print $1}'`
    iptables -I  INPUT ${RULENUM} -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
    iptables-save > /etc/sysconfig/iptables
    echo "tcp 443番ポートのアクセスを許可しました"
  fi
fi

chkconfig --add httpd
chkconfig httpd on
service httpd stop
service httpd start
