#!/bin/bash

# set Redmine.pm
mkdir -p /etc/perl/Apache/Authn
rm -f /etc/perl/Apache/Authn/Redmine.pm
ln -s $INSTALL_DIR/extra/svn/Redmine.pm /etc/perl/Apache/Authn/Redmine.pm

# Apache configs
if [ "$SSL" = "y" ]; then REPLACE_SSL="#SSL# *"; fi
if [ "$ENABLE_JENKINS" = "y" ]; then REPLACE_JENKINS="#JENKINS# *"; fi
if [ "$ALMINIUM_SUBDIR" = "y" ]; then REPLACE_DIR="#SUBDIR# *"; else REPLACE_DIR="#NO_SUBDIR# *"; fi
for FILE in $(ls etc/ | grep '.conf$')
do
  sed -e "s|#HOSTNAME#|$HOSTNAME|" \
      -e "s|#$OS# *||" \
      -e "s|$REPLACE_SSL||" \
      -e "s|$REPLACE_JENKINS||" \
      -e "s|$REPLACE_DIR||" \
      "etc/$FILE" > "$ALM_ETC_DIR/$FILE"
done

ln -sf "$ALM_ETC_DIR/passenger.conf" "/etc/apache2/mods-available/passenger.load"
ln -sf "$ALM_ETC_DIR/alminium.conf"  "/etc/apache2/sites-available/alminium.conf"

# log rotate
cp $ALM_ETC_DIR/alminium-logrotate /etc/logrotate.d/alminium

a2enmod expires
a2enmod dav_fs
a2enmod auth_mysql
a2enmod authz_svn
a2enmod proxy_http
a2enmod headers
a2enmod rewrite
a2enmod passenger
a2enmod perl
a2enmod wsgi
a2enmod cgi
a2dismod mpm_event
a2enmod mpm_prefork
a2ensite alminium.conf

service apache2 stop
service apache2 start

# vim: set ts=2 sw=2 et:
