#!/bin/bash

# # add passenger to APT repository
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
apt-get -y install apt-transport-https ca-certificates
echo deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main > /etc/apt/sources.list.d/passenger.list
chown root: /etc/apt/sources.list.d/passenger.list
# remove old passenger's info 
if [ "`ls /etc/apache2/mods-available/passenger.load 2>/dev/null`" != "" \
     -a ! -f /etc/apache2/mods-available/passenger.load ]; then
  rm -f /etc/apache2/mods*/passenger.*
fi
#  set passenger-package available
ALM_PASSSENGER_PACKAGE_AVAILABLE=1

# add ruby2.1's APT repository
apt-get -y install software-properties-common
add-apt-repository -y ppa:brightbox/ruby-ng
#if [ "`ruby --version | grep 1.9`" != "" ]; then
#  apt-get -y remove ruby1.9*
#fi

# install APT packages
apt-get -q2 update
apt-get -y install `grep -v "^#" inst-script/debian/packages.lst`
#REALLY_GEM_UPDATE_SYSTEM=1 gem update --system

# switch to ruby2.1
ruby-switch --set ruby2.1
REALLY_GEM_UPDATE_SYSTEM=1 gem update --system

# SSL
if [ "$ALM_ENABLE_SSL" = "y" ]; then
    apt-get -y install libapache2-mod-gnutls ssl-cert
    a2enmod ssl rewrite
    a2dismod gnutls
    # sslとgnutlsが両方有効化されてしまいappache2がエラーになるため後者を無効化しておく（要調査）
else
    a2dismod ssl
fi

service mysql start
